name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Go tests
        uses: jrschumacher/go-actions/ci@v1
        with:
          job: test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: jrschumacher/go-actions/ci@v1
        with:
          job: lint

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run benchmarks
        uses: jrschumacher/go-actions/ci@v1
        with:
          job: benchmark

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate project configuration
        uses: jrschumacher/go-actions/self-validate@v1