name: 'Go Actions Comment'
description: 'Posts unified CI results comment to pull requests'
author: 'Ryan Schumacher'

inputs:
  github-token:
    description: 'GitHub token for posting comments'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Post unified comment
      uses: actions/github-script@v7
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        script: |
          const actionComment = require('${{ github.action_path }}/../scripts-dist/ci-action-bundle/index.js').actionComment;
          await actionComment();