name: 'Go Actions Self-Validator'
description: 'Validates project configuration when go-actions are used in workflows'
author: 'Ryan Schumacher'

inputs:
  workflow-paths:
    description: 'Comma-separated list of workflow files to check (e.g., .github/workflows/ci.yaml,.github/workflows/release.yaml)'
    required: false
    default: '.github/workflows/*.yaml,.github/workflows/*.yml'
  comment-on-pr:
    description: 'Whether to comment on PR with validation results'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate go-actions usage
      id: validate
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Load the workflow validator directly without @actions dependencies
          const { validateWorkflows } = require('${{ github.action_path }}/../scripts-dist/self-validate-bundle/index.js');
          
          const result = validateWorkflows('.');
          
          console.log('Found go-actions usage:', result.actionsFound);
          
          // Set outputs
          core.setOutput('actions_found', result.actionsFound.join(','));
          core.setOutput('validation_failed', (!result.isValid).toString());
          
          if (!result.isValid) {
            const errorMessages = result.errors.map(error => `- ${error.message}`).join('\n');
            console.log('\n::error::Validation failed:');
            console.log(errorMessages);
            core.setOutput('error_messages', errorMessages);
            core.setFailed(`Validation failed with ${result.errors.length} error(s)`);
          } else {
            console.log('✅ All validations passed!');
          }
          
          // Generate PR comment if requested
          const commentOnPr = '${{ inputs.comment-on-pr }}' === 'true';
          if (commentOnPr) {
            try {
              // Check if this is a pull request event using environment variables
              const eventName = process.env.GITHUB_EVENT_NAME;
              if (eventName !== 'pull_request') {
                console.log('Skipping PR comment - not a pull request event');
                return;
              }
              
              // Get context information from environment variables
              const owner = process.env.GITHUB_REPOSITORY.split('/')[0];
              const repo = process.env.GITHUB_REPOSITORY.split('/')[1];
              const prNumber = process.env.GITHUB_REF_NAME.split('/')[0]; // This might not work, let's use a different approach
              
              // For PR events, we need to get the PR number differently
              const eventPath = process.env.GITHUB_EVENT_PATH;
              const event = JSON.parse(require('fs').readFileSync(eventPath, 'utf8'));
              const issueNumber = event.pull_request ? event.pull_request.number : event.issue ? event.issue.number : null;
              
              if (!issueNumber) {
                console.log('Could not determine PR/issue number');
                return;
              }
              const { WorkflowValidator } = require('${{ github.action_path }}/../scripts-dist/self-validate-bundle/index.js');
              const validator = new WorkflowValidator('.');
              const comment = validator.formatPRComment(result);
              
              // Post or update comment
              const { data: comments } = await github.rest.issues.listComments({
                owner: owner,
                repo: repo,
                issue_number: issueNumber,
              });
              
              const existingComment = comments.find(comment => 
                comment.body.includes('## 🔍 Go Actions Validation')
              );
              
              if (existingComment) {
                await github.rest.issues.updateComment({
                  owner: owner,
                  repo: repo,
                  comment_id: existingComment.id,
                  body: comment
                });
                console.log('Updated existing validation comment');
              } else {
                await github.rest.issues.createComment({
                  owner: owner,
                  repo: repo,
                  issue_number: issueNumber,
                  body: comment
                });
                console.log('Created new validation comment');
              }
            } catch (commentError) {
              console.log('Failed to post PR comment:', commentError.message);
              // Don't fail the action if commenting fails
            }
          }

    # Self-validation results are now stored for unified comment
    # Individual validation comments are consolidated into a single unified comment