package github

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/jrschumacher/go-actions/cli/internal/output"
)

const (
	dataStartMarker = "<!-- go-actions-data:"
	dataEndMarker   = "-->"
)

// CommentMarker is the identifier for go-actions comments
const CommentMarker = "# Go Actions Report"

// Coverage thresholds for test result formatting
const (
	ExcellentCoverageThreshold = 80.0
	GoodCoverageThreshold      = 60.0
	MaxLintOutputLength        = 3000
)

// titleCase capitalizes the first letter of a string (simple ASCII version)
func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// FormatComment formats CI results as a GitHub PR comment
func FormatComment(results *output.Results) string {
	if results == nil || len(results.Checks) == 0 {
		return formatEmptyComment()
	}

	var comment strings.Builder
	comment.WriteString(CommentMarker + "\n\n")

	// Status summary lines
	for _, check := range results.Checks {
		if check.Status == "skip" {
			continue
		}
		comment.WriteString(formatStatusLine(check) + "\n")
	}
	comment.WriteString("\n")

	// Details sections
	for _, check := range results.Checks {
		if check.Status == "skip" {
			continue
		}
		comment.WriteString(formatDetailsSection(check))
	}

	// Embed structured data for merge support (hidden HTML comment)
	comment.WriteString(embedResultsData(results))

	// Footer
	comment.WriteString("*🤖 This comment will update automatically as you push changes.*\n")
	comment.WriteString("*Generated by [go-actions](https://github.com/jrschumacher/go-actions)*")

	return comment.String()
}

// embedResultsData serializes results as a hidden HTML comment for later parsing
func embedResultsData(results *output.Results) string {
	data, err := json.Marshal(results)
	if err != nil {
		return ""
	}
	return fmt.Sprintf("%s%s%s\n", dataStartMarker, string(data), dataEndMarker)
}

// ParseCommentData extracts embedded results data from an existing comment body
func ParseCommentData(body string) *output.Results {
	startIdx := strings.Index(body, dataStartMarker)
	if startIdx == -1 {
		return nil
	}
	startIdx += len(dataStartMarker)

	endIdx := strings.Index(body[startIdx:], dataEndMarker)
	if endIdx == -1 {
		return nil
	}

	jsonStr := strings.TrimSpace(body[startIdx : startIdx+endIdx])
	var results output.Results
	if err := json.Unmarshal([]byte(jsonStr), &results); err != nil {
		return nil
	}
	return &results
}

// MergeResults merges new check results into existing results.
// New results for a check name replace existing results for that name.
func MergeResults(existing, incoming *output.Results) *output.Results {
	if existing == nil {
		return incoming
	}
	if incoming == nil {
		return existing
	}

	merged := &output.Results{
		Status: "pass",
	}

	// Start with existing checks
	checkMap := make(map[string]output.CheckResult)
	var order []string
	for _, check := range existing.Checks {
		checkMap[check.Name] = check
		order = append(order, check.Name)
	}

	// Merge in incoming checks (replace or append)
	for _, check := range incoming.Checks {
		if _, exists := checkMap[check.Name]; !exists {
			order = append(order, check.Name)
		}
		checkMap[check.Name] = check
	}

	// Build merged checks in order
	for _, name := range order {
		check := checkMap[name]
		merged.Checks = append(merged.Checks, check)
		if check.Status == "fail" || check.Status == "error" {
			if merged.Status == "pass" {
				merged.Status = check.Status
			}
		}
	}

	return merged
}

// formatStatusLine creates a single status line for a check
func formatStatusLine(check output.CheckResult) string {
	var line string

	switch check.Name {
	case "test":
		icon := "✅"
		if check.Status == "fail" || check.Status == "error" {
			icon = "❌"
		}
		line = fmt.Sprintf("%s **Tests**", icon)
		if check.Coverage > 0 {
			line += fmt.Sprintf(" (%.1f%% coverage)", check.Coverage)
		} else if check.Status == "fail" {
			line += " (failed)"
		}

	case "lint":
		icon := "✅"
		if check.Status == "fail" || check.Status == "error" {
			icon = "🚨"
		}
		line = fmt.Sprintf("%s **Lint**", icon)
		if check.Status == "fail" || check.Status == "error" {
			line += " **- Issues Found!**"
		}

	case "security":
		icon := "✅"
		if check.Status == "fail" || check.Status == "error" {
			icon = "🚨"
		}
		line = fmt.Sprintf("%s **Security**", icon)
		if check.Status == "fail" || check.Status == "error" {
			count := check.Vulnerabilities
			plural := "ies"
			if count == 1 {
				plural = "y"
			}
			line += fmt.Sprintf(" **- %d Vulnerabilit%s Found!**", count, plural)
		}

	case "benchmark":
		icon := "✅"
		if check.Status == "fail" || check.Status == "error" {
			icon = "❌"
		}
		line = fmt.Sprintf("%s **Benchmarks**", icon)
		if check.Status == "fail" {
			line += " (failed)"
		}

	default:
		icon := "✅"
		if check.Status == "fail" || check.Status == "error" {
			icon = "❌"
		}
		line = fmt.Sprintf("%s **%s**", icon, titleCase(check.Name))
	}

	return line
}

// formatDetailsSection creates a collapsible details section for a check
func formatDetailsSection(check output.CheckResult) string {
	var section strings.Builder

	switch check.Name {
	case "test":
		section.WriteString(formatTestDetails(check))
	case "lint":
		section.WriteString(formatLintDetails(check))
	case "security":
		section.WriteString(formatSecurityDetails(check))
	case "benchmark":
		section.WriteString(formatBenchmarkDetails(check))
	}

	return section.String()
}

// formatTestDetails formats the test results section
func formatTestDetails(check output.CheckResult) string {
	var details strings.Builder

	if check.Status == "pass" {
		if check.Coverage > 0 {
			emoji := getCoverageEmoji(check.Coverage)
			coverageMsg := getCoverageMessage(check.Coverage)

			details.WriteString("<details><summary>Test Details</summary>\n\n")
			fmt.Fprintf(&details, "**Coverage: %.1f%%**\n\n", check.Coverage)
			fmt.Fprintf(&details, "%s %s\n\n", emoji, coverageMsg)
			details.WriteString("</details>\n\n")
		} else {
			details.WriteString("<details><summary>Test Details</summary>\n\n")
			details.WriteString("All tests passed successfully!\n\n")
			details.WriteString("</details>\n\n")
		}
	} else {
		details.WriteString("<details open><summary>Test Issues</summary>\n\n")
		details.WriteString("**Tests failed!**\n\n")
		if check.Message != "" {
			fmt.Fprintf(&details, "**Error:** %s\n\n", check.Message)
		} else {
			details.WriteString("Please check the test logs for details.\n\n")
		}
		details.WriteString("</details>\n\n")
	}

	return details.String()
}

// formatLintDetails formats the lint results section
func formatLintDetails(check output.CheckResult) string {
	var details strings.Builder

	if check.Status == "pass" {
		details.WriteString("<details><summary>Lint Details</summary>\n\n")
		details.WriteString("Code quality checks passed!\n\n")
		details.WriteString("</details>\n\n")
	} else {
		details.WriteString("<details open><summary>🚨 Lint Issues Found</summary>\n\n")
		details.WriteString("**Code quality checks failed!**")

		if check.Message != "" {
			issuesOutput := check.Message
			// Truncate if too long (GitHub comment limit considerations)
			if len(issuesOutput) > MaxLintOutputLength {
				issuesOutput = issuesOutput[:MaxLintOutputLength] + "\n\n... (truncated, see workflow logs for full output)"
			}
			fmt.Fprintf(&details, "\n\n```\n%s\n```\n", issuesOutput)
		} else {
			details.WriteString("\n\nPlease check the workflow logs for details.")
		}

		details.WriteString("\n\n</details>\n\n")
	}

	return details.String()
}

// formatSecurityDetails formats the security scan results section
func formatSecurityDetails(check output.CheckResult) string {
	var details strings.Builder

	if check.Status == "pass" {
		details.WriteString("<details><summary>Security Details</summary>\n\n")
		details.WriteString("🛡️ No known vulnerabilities found in dependencies!\n\n")
		details.WriteString("**Tool:** govulncheck (Go Vulnerability Database)\n\n")
		details.WriteString("</details>\n\n")
	} else {
		count := check.Vulnerabilities
		plural := "ies"
		if count == 1 {
			plural = "y"
		}

		fmt.Fprintf(&details, "<details open><summary>🚨 %d Vulnerabilit%s Found</summary>\n\n", count, plural)
		details.WriteString("**Security scan detected known CVEs in your dependencies!**")

		if check.Message != "" {
			fmt.Fprintf(&details, "\n\n%s\n", check.Message)
		} else {
			details.WriteString("\n\nPlease check the workflow logs for details.")
		}

		details.WriteString("\n\n</details>\n\n")
	}

	return details.String()
}

// formatBenchmarkDetails formats the benchmark results section
func formatBenchmarkDetails(check output.CheckResult) string {
	var details strings.Builder

	if check.Status == "pass" {
		details.WriteString("<details><summary>Benchmark Details</summary>\n\n")
		details.WriteString("Benchmarks completed successfully!\n\n")
		details.WriteString("</details>\n\n")
	} else {
		details.WriteString("<details open><summary>Benchmark Issues</summary>\n\n")
		details.WriteString("**Benchmarks failed!**\n\n")
		if check.Message != "" {
			fmt.Fprintf(&details, "**Error:** %s\n\n", check.Message)
		}
		details.WriteString("</details>\n\n")
	}

	return details.String()
}

// getCoverageEmoji returns an emoji based on coverage percentage
func getCoverageEmoji(coverage float64) string {
	if coverage >= ExcellentCoverageThreshold {
		return "🎉"
	} else if coverage >= GoodCoverageThreshold {
		return "⚠️"
	}
	return "🚨"
}

// getCoverageMessage returns a message based on coverage percentage
func getCoverageMessage(coverage float64) string {
	if coverage >= ExcellentCoverageThreshold {
		return "Excellent test coverage!"
	} else if coverage >= GoodCoverageThreshold {
		return "Good coverage, consider adding more tests."
	}
	return "Low test coverage detected. Please add more tests."
}

// formatEmptyComment returns a comment for when no results are available
func formatEmptyComment() string {
	return `# Go Actions Report

⏳ **Pending**

<details><summary>Details</summary>

No CI jobs have run yet. Results will appear here as jobs complete.

</details>

*🤖 This comment will update automatically as you push changes.*
*Generated by [go-actions](https://github.com/jrschumacher/go-actions)*`
}

// FormatProcessingComment returns a comment for when jobs are running
func FormatProcessingComment() string {
	return `# Go Actions Report

🔄 **Running...**

Validation is in progress. Results will appear here shortly.

*🤖 This comment will update automatically as jobs complete.*
*Generated by [go-actions](https://github.com/jrschumacher/go-actions)*`
}
