name: 'Go CI Actions'
description: 'CI workflows for Go projects - test, lint, and benchmark'
author: 'Ryan Schumacher'

inputs:
  job:
    description: 'Job type to run: test, lint, or benchmark'
    required: true
  go-version:
    description: 'Go version to use (all jobs). Defaults to version from go.mod'
    required: false
    default: ''
  go-version-file:
    description: 'Path to file containing Go version (all jobs). Defaults to go.mod'
    required: false
    default: 'go.mod'
  working-directory:
    description: 'Working directory (all jobs)'
    required: false
    default: '.'
  
  # Test job specific inputs
  test-args:
    description: 'Additional arguments for go test (test job only)'
    required: false
    default: '-v -race -coverprofile=coverage.out'
  
  # Lint job specific inputs
  golangci-lint-version:
    description: 'golangci-lint version (lint job only). Use v2.1.0+ or v2/latest (auto-converted to v2.1.0)'
    required: false
    default: 'v2.1.0'
  lint-args:
    description: 'Additional arguments for golangci-lint (lint job only)'
    required: false
    default: ''
  
  # Benchmark job specific inputs
  benchmark-args:
    description: 'Additional arguments for go test -bench (benchmark job only)'
    required: false
    default: '-bench=. -benchmem'
  benchmark-count:
    description: 'Number of benchmark runs (benchmark job only)'
    required: false
    default: '5'

outputs:
  coverage:
    description: "Test coverage percentage"
    value: ${{ steps.coverage.outputs.coverage }}

runs:
  using: "composite"
  steps:
    - name: Validate job input
      shell: bash
      run: |
        valid_jobs="test lint benchmark"
        job="${{ inputs.job }}"
        if [[ ! " $valid_jobs " =~ " $job " ]]; then
          echo "::error::Invalid job type: $job. Valid options are: $valid_jobs"
          exit 1
        fi

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ !inputs.go-version && inputs.go-version-file || '' }}

    # Test job
    - name: Run tests
      if: inputs.job == 'test'
      id: test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Running Go tests..."
        go test ${{ inputs.test-args }} ./...

    - name: Extract coverage and store results
      if: inputs.job == 'test'
      id: coverage
      uses: actions/github-script@v7
      with:
        script: |
          const { extractCoverage, UnifiedPRComment, updateUnifiedComment } = require('${{ github.action_path }}/../scripts-dist/ci-action-bundle/index.js');
          const workingDir = '${{ inputs.working-directory }}' || '.';
          
          const result = extractCoverage(workingDir);
          
          if (result.hasCoverage && result.coverage !== null) {
            console.log(`Coverage: ${result.coverage}%`);
            core.setOutput('coverage', result.coverage.toString());
          } else {
            console.log('No coverage data found');
            core.setOutput('coverage', '0');
          }
          
          // Store test results for unified comment
          const testResult = {
            status: '${{ steps.test.outcome }}' === 'success' ? 'success' : 'failure',
            coverage: result.hasCoverage && result.coverage !== null ? `${result.coverage}%` : undefined,
            error: '${{ steps.test.outcome }}' !== 'success' ? 'Test execution failed' : undefined
          };
          
          await UnifiedPRComment.storeResults('test', testResult);
          console.log('Stored test results for unified comment');

    # Benchmark job
    - name: Run benchmarks and store results
      if: inputs.job == 'benchmark'
      id: benchmark
      uses: actions/github-script@v7
      with:
        script: |
          const { runBenchmarks, UnifiedPRComment, updateUnifiedComment } = require('${{ github.action_path }}/../scripts-dist/ci-action-bundle/index.js');
          const workingDir = '${{ inputs.working-directory }}' || '.';
          const benchmarkArgs = '${{ inputs.benchmark-args }}' || '-bench=. -benchmem';
          const benchmarkCount = parseInt('${{ inputs.benchmark-count }}') || 5;
          
          try {
            const result = runBenchmarks(workingDir, benchmarkArgs, benchmarkCount);
            console.log('Benchmark results:', result);
            
            // Store benchmark results for unified comment
            const benchmarkResult = {
              status: 'success',
              config: {
                args: benchmarkArgs,
                count: benchmarkCount
              }
            };
            
            await UnifiedPRComment.storeResults('benchmark', benchmarkResult);
            
          } catch (error) {
            console.error('Benchmark failed:', error.message);
            
            // Store failure results
            const benchmarkResult = {
              status: 'failure',
              error: error.message,
              config: {
                args: benchmarkArgs,
                count: benchmarkCount
              }
            };
            
            await UnifiedPRComment.storeResults('benchmark', benchmarkResult);
            throw error; // Re-throw to fail the job
          }
          
          console.log('Stored benchmark results for unified comment');

    # Lint job  
    - name: Normalize golangci-lint version
      if: inputs.job == 'lint'
      shell: bash
      id: normalize-version
      run: |
        version="${{ inputs.golangci-lint-version }}"
        # Convert generic v2 to specific version for golangci-lint-action@v8 compatibility
        if [ "$version" = "v2" ] || [ "$version" = "latest" ]; then
          version="v2.1.0"
        fi
        echo "normalized-version=$version" >> $GITHUB_OUTPUT
        echo "Using golangci-lint version: $version"

    - name: Run golangci-lint
      if: inputs.job == 'lint'
      id: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: ${{ steps.normalize-version.outputs.normalized-version }}
        working-directory: ${{ inputs.working-directory }}
        args: ${{ inputs.lint-args }}

    - name: Store lint results
      if: inputs.job == 'lint' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const { UnifiedPRComment, updateUnifiedComment } = require('${{ github.action_path }}/../scripts-dist/ci-action-bundle/index.js');
          
          // Capture golangci-lint results
          const lintOutcome = '${{ steps.golangci-lint.outcome }}';
          const lintResult = {
            status: lintOutcome === 'success' ? 'success' : 'failure',
            error: lintOutcome !== 'success' ? 'Linting issues found - check logs for details' : undefined
          };
          
          await UnifiedPRComment.storeResults('lint', lintResult);
          console.log('Stored lint results for unified comment');

    # Results are automatically stored and unified comment is updated by each job
    # All CI results (test, lint, benchmark) appear in a single "Go Actions Report" comment